# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSG Build to Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # cache the dependencies from any node_modules directory
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/package-lock.json
            **/.production
          key: node_modules-${{ hashFiles('**/package.json') }}

      - name: Install deps
        run: yarn

      - name: Build
        env:
          NULLSTACK_PROJECT_NAME: 'sales-page'
          NULLSTACK_PROJECT_DOMAIN: 'tipscode2.github.io/sales-page'
          NULLSTACK_PROJECT_COLOR: '#D22365'
          NULLSTACK_WORKER_CDN: '/sales-page'
          NULLSTACK_WORKER_ENABLED: ''
        run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: master
          folder: ssg